name: kashmirimarsiya
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  google_fonts: ^2.3.3
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  url_launcher: ^6.1.5
  marquee: ^2.2.3
  intl: ^0.17.0
  just_audio: ^0.9.34
  just_audio_background: ^0.0.1-beta.10
  audio_session: ^0.1.6
  permission_handler: ^11.0.0
  flutter_svg: ^2.0.7 
  syncfusion_flutter_pdfviewer: ^20.4.54




  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/karbala.jpg
