name: Marsiya
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+5

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  google_fonts: ^5.1.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  marquee: ^2.2.3
  intl: ^0.18.1
  just_audio: ^0.9.34
  just_audio_background: ^0.0.1-beta.10
  audio_session: ^0.1.6
  permission_handler: ^11.0.0
  flutter_svg: ^2.0.7 
  flutter_staggered_animations: ^1.1.1
  typed_data: ^1.3.0  # For Uint8List
  share_plus: ^7.0.2
  fluttertoast: ^8.0.9
  flutter_pdfview: ^1.4.0
  path_provider: ^2.1.5




  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/unnamed.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/unnamed.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/unnamed.png"
  windows:
    generate: true
    image_path: "assets/images/unnamed.png"
  macos:
    generate: true
    image_path: "assets/images/unnamed.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/karbala.jpg
    - assets/images/unnamed.png
